"""
Deterministic client order IDs -- the only defence against a timeout creating a
duplicate entry.
"""

from __future__ import annotations

import pytest

from cf_bot.ids import (
    PURPOSE_ENTRY,
    PURPOSE_FLATTEN,
    PURPOSE_STOP,
    PURPOSE_TARGET,
    client_order_id,
    is_entry,
    is_ours,
    purpose_of,
)


def test_the_same_signal_always_produces_the_same_id():
    """The core property. A retry after a timeout must reuse the id."""
    a = client_order_id("BTC/USDT:USDT", 1717000000000, "long", PURPOSE_ENTRY)
    b = client_order_id("BTC/USDT:USDT", 1717000000000, "long", PURPOSE_ENTRY)
    assert a == b


def test_ids_are_stable_across_processes():
    """
    Pinned to a literal, deliberately.

    The id must come from sha256, not Python's salted hash() -- with hash() the
    value would differ on every process start and the duplicate protection would
    silently evaporate on restart. A hardcoded expectation is the only way to
    catch that, because within one process a salted hash also looks stable.

    If this ever fails, IDs generated by the old build will no longer match the
    new one, and in-flight orders lose their duplicate protection during the
    deploy. Do not update the literal without understanding that.
    """
    assert (
        client_order_id("BTC/USDT:USDT", 1717000000000, "long", PURPOSE_ENTRY)
        == "cfee0ef6cda76828cbce388"
    )


def test_id_is_a_pure_function_of_its_inputs():
    base = client_order_id("BTC/USDT:USDT", 1717000000000, "long", PURPOSE_ENTRY)
    assert client_order_id("ETH/USDT:USDT", 1717000000000, "long", PURPOSE_ENTRY) != base
    assert client_order_id("BTC/USDT:USDT", 1717000000001, "long", PURPOSE_ENTRY) != base
    assert client_order_id("BTC/USDT:USDT", 1717000000000, "short", PURPOSE_ENTRY) != base
    assert client_order_id("BTC/USDT:USDT", 1717000000000, "long", PURPOSE_STOP) != base


@pytest.mark.parametrize(
    "purpose", [PURPOSE_ENTRY, PURPOSE_STOP, PURPOSE_TARGET, PURPOSE_FLATTEN]
)
def test_every_purpose_produces_a_recognisable_id(purpose):
    oid = client_order_id("BTC/USDT:USDT", 1, "long", purpose)
    assert is_ours(oid)
    assert purpose_of(oid) == purpose


def test_ids_fit_bitgets_length_limit():
    """Bitget caps clientOid at 64 characters."""
    oid = client_order_id("SOMEVERYLONGSYMBOL/USDT:USDT", 1717000000000, "long", PURPOSE_ENTRY)
    assert len(oid) <= 64
    assert oid.isalnum()


def test_only_entry_ids_report_as_entries():
    assert is_entry(client_order_id("BTC/USDT:USDT", 1, "long", PURPOSE_ENTRY)) is True
    assert is_entry(client_order_id("BTC/USDT:USDT", 1, "long", PURPOSE_STOP)) is False


@pytest.mark.parametrize("foreign", [None, "", "manual-order-1", "cf", "xyz123", "cfz" + "a" * 20])
def test_foreign_ids_are_not_recognised_as_ours(foreign):
    assert is_entry(foreign) is False


def test_unknown_purpose_is_rejected():
    with pytest.raises(ValueError):
        client_order_id("BTC/USDT:USDT", 1, "long", "x")


@pytest.mark.parametrize("bad_side", ["buy", "sell", "LONG", ""])
def test_side_must_be_long_or_short(bad_side):
    with pytest.raises(ValueError):
        client_order_id("BTC/USDT:USDT", 1, bad_side, PURPOSE_ENTRY)


def test_missing_symbol_is_rejected():
    with pytest.raises(ValueError):
        client_order_id("", 1, "long", PURPOSE_ENTRY)
